name: Update Enum in ProjectA

on:
  push:
    branches:
      - main

jobs:
  update-enum:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Update Enum in Other Projects
        run: |
          if [ "${{ github.event.repository.name }}" == "ProjectA" ]; then
            echo "Update colors_enum.cs in ProjectB, ProjectC, and ProjectD"
            # Clone ProjectB and update colors_enum.cs
            git clone git@github.com:kuoyuhsiang/ProjectB.git
            cp ProjectA/colors_enum.cs ProjectB/
            cd ProjectB
            git config user.name "kuoyuhsiang"
            git config user.email "were1122was@gmail.com"
            git add colors_enum.cs
            git commit -m "Update enum in ProjectB"
            git push
            cd ..
            # Clone ProjectC and update colors_enum.cs (repeat similar commands)
            git clone git@github.com:kuoyuhsiang/ProjectC.git
            cp ProjectA/colors_enum.cs ProjectC/
            cd ProjectC
            git config user.name "kuoyuhsiang"
            git config user.email "were1122was@gmail.com"
            git add colors_enum.cs
            git commit -m "Update enum in ProjectC"
            git push
            cd ..
            # Clone ProjectD and update colors_enum.cs (repeat similar commands)
            git clone git@github.com:kuoyuhsiang/ProjectD.git
            cp ProjectA/colors_enum.cs ProjectD/
            cd ProjectD
            git config user.name "kuoyuhsiang"
            git config user.email "were1122was@gmail.com"
            git add colors_enum.cs
            git commit -m "Update enum in ProjectD"
            git push
            cd ..
          fi
