name: Update Enum in ProjectA

on:
  push:
    branches:
      - main

jobs:
  update-enum:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Update Enum in Other Projects
        run: |
          if [ "${{ github.event.repository.name }}" == "ProjectA" ]; then
            echo "Update colors_enum.cs in ProjectB, ProjectC, and ProjectD"
            
            # Update colors_enum.cs in ProjectB
            git clone https://github.com/kuoyuhsiang/ProjectB.git
            cd ProjectB
            git pull
            cp ../colors_enum.cs ./
            git config user.name "kuoyuhsiang"
            git config user.email "were1122was@gmail.com"
            git add colors_enum.cs
            git commit -m "Update enum in ProjectB"
            git push
            cd ..

            # Update colors_enum.cs in ProjectC (similar commands)
            git clone https://github.com/kuoyuhsiang/ProjectC.git
            cd ProjectC
            git pull
            cp ../colors_enum.cs ./
            git config user.name "kuoyuhsiang"
            git config user.email "were1122was@gmail.com"
            git add colors_enum.cs
            git commit -m "Update enum in ProjectC"
            git push
            cd ..

            # Update colors_enum.cs in ProjectD (similar commands)
            git clone https://github.com/kuoyuhsiang/ProjectD.git
            cd ProjectD
            git pull
            cp ../colors_enum.cs ./
            git config user.name "kuoyuhsiang"
            git config user.email "were1122was@gmail.com"
            git add colors_enum.cs
            git commit -m "Update enum in ProjectD"
            git push
          fi
